version: '3.9'

services:
  db:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'john.doe@sample.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
    ports:
      - 7172:80
